import type { AuditCategory, AuditOutcome } from '@prisma/client';

export const AUDIT_EVENT_TYPES = {
  LOGIN_STARTED: 'auth.login.started',
  LOGIN_SUCCEEDED: 'auth.login.succeeded',
  LOGIN_DENIED: 'auth.login.denied',
  LOGOUT: 'auth.logout',
  TENANT_SWITCH_SUCCEEDED: 'tenant.switch.succeeded',
  TENANT_SWITCH_DENIED: 'tenant.switch.denied',
  MEMBERSHIP_INVITED: 'membership.invited',
  MEMBERSHIP_ACCEPTED: 'membership.accepted',
  MEMBERSHIP_SUSPENDED: 'membership.suspended',
  ROLE_ASSIGNED: 'role.assigned',
  PERMISSION_DENIED: 'permission.denied',
} as const;

export type AuditEventType =
  (typeof AUDIT_EVENT_TYPES)[keyof typeof AUDIT_EVENT_TYPES];

export const AUDIT_EVENT_VERSIONS: Record<AuditEventType, number> = {
  [AUDIT_EVENT_TYPES.LOGIN_STARTED]: 1,
  [AUDIT_EVENT_TYPES.LOGIN_SUCCEEDED]: 1,
  [AUDIT_EVENT_TYPES.LOGIN_DENIED]: 1,
  [AUDIT_EVENT_TYPES.LOGOUT]: 1,
  [AUDIT_EVENT_TYPES.TENANT_SWITCH_SUCCEEDED]: 1,
  [AUDIT_EVENT_TYPES.TENANT_SWITCH_DENIED]: 1,
  [AUDIT_EVENT_TYPES.MEMBERSHIP_INVITED]: 1,
  [AUDIT_EVENT_TYPES.MEMBERSHIP_ACCEPTED]: 1,
  [AUDIT_EVENT_TYPES.MEMBERSHIP_SUSPENDED]: 1,
  [AUDIT_EVENT_TYPES.ROLE_ASSIGNED]: 1,
  [AUDIT_EVENT_TYPES.PERMISSION_DENIED]: 1,
};

export const AUDIT_CATEGORY: Record<AuditEventType, AuditCategory> = {
  [AUDIT_EVENT_TYPES.LOGIN_STARTED]: 'AUDIT',
  [AUDIT_EVENT_TYPES.LOGIN_SUCCEEDED]: 'AUDIT',
  [AUDIT_EVENT_TYPES.LOGIN_DENIED]: 'SECURITY',
  [AUDIT_EVENT_TYPES.LOGOUT]: 'AUDIT',
  [AUDIT_EVENT_TYPES.TENANT_SWITCH_SUCCEEDED]: 'AUDIT',
  [AUDIT_EVENT_TYPES.TENANT_SWITCH_DENIED]: 'SECURITY',
  [AUDIT_EVENT_TYPES.MEMBERSHIP_INVITED]: 'AUDIT',
  [AUDIT_EVENT_TYPES.MEMBERSHIP_ACCEPTED]: 'AUDIT',
  [AUDIT_EVENT_TYPES.MEMBERSHIP_SUSPENDED]: 'SECURITY',
  [AUDIT_EVENT_TYPES.ROLE_ASSIGNED]: 'AUDIT',
  [AUDIT_EVENT_TYPES.PERMISSION_DENIED]: 'SECURITY',
};

export const AUDIT_DEFAULT_OUTCOME: Record<
  AuditEventType,
  AuditOutcome
> = {
  [AUDIT_EVENT_TYPES.LOGIN_STARTED]: 'SUCCEEDED',
  [AUDIT_EVENT_TYPES.LOGIN_SUCCEEDED]: 'SUCCEEDED',
  [AUDIT_EVENT_TYPES.LOGIN_DENIED]: 'DENIED',
  [AUDIT_EVENT_TYPES.LOGOUT]: 'SUCCEEDED',
  [AUDIT_EVENT_TYPES.TENANT_SWITCH_SUCCEEDED]: 'SUCCEEDED',
  [AUDIT_EVENT_TYPES.TENANT_SWITCH_DENIED]: 'DENIED',
  [AUDIT_EVENT_TYPES.MEMBERSHIP_INVITED]: 'SUCCEEDED',
  [AUDIT_EVENT_TYPES.MEMBERSHIP_ACCEPTED]: 'SUCCEEDED',
  [AUDIT_EVENT_TYPES.MEMBERSHIP_SUSPENDED]: 'SUCCEEDED',
  [AUDIT_EVENT_TYPES.ROLE_ASSIGNED]: 'SUCCEEDED',
  [AUDIT_EVENT_TYPES.PERMISSION_DENIED]: 'DENIED',
};
