export const BOOTSTRAP_ROLE_KEY_GLOBAL = 'platform.admin';
export const BOOTSTRAP_ROLE_KEY_TENANT = 'tenant.admin';
export const BOOTSTRAP_ROLE_NAME_GLOBAL = 'Platform Administrator';
export const BOOTSTRAP_ROLE_NAME_TENANT = 'Tenant Administrator';

export const BOOTSTRAP_DEFAULT_MFA_MAX_AGE_SECONDS = 15 * 60;

export const BOOTSTRAP_DENIED_REASON = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  SUBJECT_MISMATCH: 'SUBJECT_MISMATCH',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_STALE: 'MFA_STALE',
  SECRET_MISMATCH: 'SECRET_MISMATCH',
  ALREADY_BOOTSTRAPPED: 'ALREADY_BOOTSTRAPPED',
  PLATFORM_ADMIN_EXISTS: 'PLATFORM_ADMIN_EXISTS',
} as const;

export type BootstrapDeniedReason =
  (typeof BOOTSTRAP_DENIED_REASON)[keyof typeof BOOTSTRAP_DENIED_REASON];
